language: node_js
node_js:
        - "stable"
sudo: false
    
branches:
    only:
        - develop
    except:
        - master

install: 
        - npm install
script: 
        - npm run build
        - npm run clean
